SELECT MONTH(k.KELUAR) BULAN
     , SUM(CASE WHEN r.JENIS_KUNJUNGAN = 3 THEN 1 ELSE 0 END) RAWATINAP

FROM pendaftaran.kunjungan k
JOIN pendaftaran.pendaftaran p ON p.NOMOR=k.NOPEN
JOIN master.ruangan r ON r.ID=k.RUANGAN AND r.JENIS_KUNJUNGAN IN(3)
WHERE k.MASUK BETWEEN '2023-01-01' AND NOW()
AND k.STATUS IN(1,2) AND p.STATUS IN(1,2)
GROUP BY MONTH(k.KELUAR)
ORDER BY MONTH(k.KELUAR)
