SELECT DATE_FORMAT(k.MASUK, '%M') TANGGGAL
     , SUM(CASE WHEN r.JENIS_KUNJUNGAN = 1 THEN 1 ELSE 0 END) RAWATJALAN
     , SUM(CASE WHEN r.JENIS_KUNJUNGAN = 3 THEN 1 ELSE 0 END) RAWATINAP
FROM pendaftaran.kunjungan k
JOIN pendaftaran.pendaftaran p ON p.NOMOR=k.NOPEN
JOIN master.ruangan r ON r.ID=k.RUANGAN
WHERE k.MASUK BETWEEN '2023-01-01' AND NOW()

GROUP BY  DATE_FORMAT(k.MASUK, '%M')
