SELECT 
DATE_FORMAT(kns.TANGGAL, '%M') BULAN
, COUNT(*) KONSULIBS
FROM pendaftaran.kunjungan k 
JOIN pendaftaran.konsul kns ON kns.NOMOR=k.REF AND k.`STATUS` IN(1,2)
WHERE kns.TUJUAN LIKE '1010701%' AND kns.TANGGAL BETWEEN '2023-01-01' AND '2023-05-31'
AND kns.`STATUS`!=0
GROUP BY DATE_FORMAT(kns.TANGGAL, '%M')