 #DILAYANI
SELECT
    p.NOMOR NOPEN
, IF(pj.JENIS = 1, 'NON JKN', IF(pj.JENIS=2, 'JKN', 'NON JKN')) JENISPASIEN
, ktp.NOMOR NIK
, pr.RUANGAN_PENJAMIN KODEPOLI
, rg.DESKRIPSI NAMAPOLI
, IF(DATE_FORMAT(p.TANGGAL,'%d-%m-%Y')=DATE_FORMAT(pd.TANGGAL,'%d-%m-%Y'),'1','0') PASIENBARU
, pd.NORM
, p.TANGGAL TGLPERIKSA
, kd.DPJP_PENJAMIN KODEDOKTERBPJS
, CONCAT(jdh.JAM_MULAI,'-',jdh.JAM_SELESAI) JAMPRAKTEKDOKTER
, 0 JENIS_KUNJUNGAN
, IF(srp.NOMOR IS NULL, pj.NO_SURAT,'-') NOMORREFERENSI
, ROW_NUMBER()OVER(PARTITION BY DATE(p.TANGGAL) ORDER BY p.TANGGAL) NOMORANTREAN
, ROW_NUMBER()OVER(PARTITION BY DATE(p.TANGGAL) ORDER BY p.TANGGAL)  ANGKANTREAN
, CONCAT(
	FLOOR(HOUR(TIMEDIFF(p.TANGGAL,k.KELUAR)) / 24), ':',
	MOD(HOUR(TIMEDIFF(p.TANGGAL,k.KELUAR)), 24), ':',
	MINUTE(TIMEDIFF(p.TANGGAL,k.KELUAR)), '') AS ESTIMASIDILAYANI
, 0 KETERANGAN
FROM pendaftaran.kunjungan k
LEFT JOIN pendaftaran.pendaftaran p ON p.NOMOR=k.NOPEN
LEFT JOIN pendaftaran.tujuan_pasien tp ON tp.NOPEN=p.NOMOR
LEFT JOIN pendaftaran.penjamin pj ON pj.NOPEN=p.NOMOR
LEFT JOIN master.kartu_identitas_pasien ktp ON ktp.NORM=p.NORM
LEFT JOIN master.ruangan rg ON rg.ID=k.RUANGAN
LEFT JOIN master.penjamin_ruangan pr ON pr.RUANGAN_RS=rg.ID
LEFT JOIN master.pasien pd ON pd.NORM=p.NORM
LEFT JOIN penjamin_rs.dpjp kd ON kd.DPJP_RS=k.DPJP
LEFT JOIN regonline.jadwal_dokter_hfis jdh ON jdh.KD_DOKTER=kd.DPJP_PENJAMIN
LEFT JOIN pendaftaran.surat_rujukan_pasien srp ON srp.NORM=p.NORM AND srp.NOMOR LIKE '2502R%'
WHERE p.TANGGAL BETWEEN '2023-05-29' AND '2023-05-31'
AND k.RUANGAN LIKE '1010201%'
AND k.STATUS = 2
GROUP BY k.NOMOR
ORDER BY p.TANGGAL, NOMORANTREAN ;

 #TIDAKDILAYANI
SELECT
    p.NOMOR NOPEN
, IF(pj.JENIS = 1, 'NON JKN', IF(pj.JENIS=2, 'JKN', 'NON JKN')) JENISPASIEN
, ktp.NOMOR NIK
, pr.RUANGAN_PENJAMIN KODEPOLI
, rg.DESKRIPSI NAMAPOLI
, IF(DATE_FORMAT(p.TANGGAL,'%d-%m-%Y')=DATE_FORMAT(pd.TANGGAL,'%d-%m-%Y'),'1','0') PASIENBARU
, pd.NORM
, k.MASUK TGLPERIKSA
, kd.DPJP_PENJAMIN KODEDOKTERBPJS
, CONCAT(jdh.JAM_MULAI,'-',jdh.JAM_SELESAI) JAMPRAKTEKDOKTER
, 0 JENIS_KUNJUNGAN
, IF(srp.NOMOR IS NULL, pj.NO_SURAT,'-') NOMORREFERENSI
, ROW_NUMBER()OVER(PARTITION BY DATE(p.TANGGAL) ORDER BY p.TANGGAL) NOMORANTREAN
, ROW_NUMBER()OVER(PARTITION BY DATE(p.TANGGAL) ORDER BY p.TANGGAL)  ANGKANTREAN
, CONCAT(
	FLOOR(HOUR(TIMEDIFF(k.MASUK,p.TANGGAL)) / 24), ':',
	MOD(HOUR(TIMEDIFF(k.MASUK,p.TANGGAL)), 24), ':',
	MINUTE(TIMEDIFF(k.MASUK,p.TANGGAL)), '') AS ESTIMASIDILAYANI
, 0 KETERANGAN
FROM pendaftaran.kunjungan k
LEFT JOIN pendaftaran.pendaftaran p ON p.NOMOR=k.NOPEN
LEFT JOIN pendaftaran.tujuan_pasien tp ON tp.NOPEN=p.NOMOR
LEFT JOIN pendaftaran.penjamin pj ON pj.NOPEN=p.NOMOR
LEFT JOIN master.kartu_identitas_pasien ktp ON ktp.NORM=p.NORM
LEFT JOIN master.ruangan rg ON rg.ID=k.RUANGAN
LEFT JOIN master.penjamin_ruangan pr ON pr.RUANGAN_RS=rg.ID
LEFT JOIN master.pasien pd ON pd.NORM=p.NORM
LEFT JOIN penjamin_rs.dpjp kd ON kd.DPJP_RS=k.DPJP
LEFT JOIN regonline.jadwal_dokter_hfis jdh ON jdh.KD_DOKTER=kd.DPJP_PENJAMIN
LEFT JOIN pendaftaran.surat_rujukan_pasien srp ON srp.NORM=p.NORM AND srp.NOMOR LIKE '2502R%'
WHERE p.TANGGAL BETWEEN '2023-05-29' AND '2023-05-31'
AND k.RUANGAN LIKE '1010201%'
AND k.STATUS = 0
GROUP BY p.NOMOR
ORDER BY k.MASUK, NOMORANTREAN;